const ASYNC_START = "ASYNC_START";
const ASYNC_END = "ASYNC_END";
const UPDATE_FIELD = "UPDATE_FIELD";
const CLEAR_UPDATED_FIELD = "CLEAR_UPDATED_FIELD";
const LOGIN = "LOGIN";
const LOGIN_DETAIL = "LOGIN_DETAIL";
const ON_LOAD_MAP = "ON_LOAD_MAP";
const ON_LOAD_USERMAP = "ON_LOAD_USERMAP";
const HOME_PAGE_LOADED = "HOME_PAGE_LOADED";
const ON_LOAD_WATCHID = "ON_LOAD_WATCHID";

export {
    ASYNC_START,
    ASYNC_END,
    UPDATE_FIELD,
    CLEAR_UPDATED_FIELD,
    LOGIN,
    LOGIN_DETAIL,
    ON_LOAD_MAP,
    ON_LOAD_USERMAP,
    HOME_PAGE_LOADED,
    ON_LOAD_WATCHID
}